name: Push To Server


on:
  push:
#    branches: [main]
  workflow_dispatch:


jobs:

  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{  secrets.HOST  }}
        username: ${{  secrets.USERNAME  }}
        key: ${{  secrets.SSH_PRIVATE_KEY  }}
        port: 22
        script: |
          cd /home/miuisr/htdocs/miuisr.ml
          git pull origin
          git status
